// <auto-generated />
using Cinema2026.Repo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema2026.Repo.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cinema2026.Repo.Models.AdminUser", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("AdminLevel")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Adminuser");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.MovieHall", b =>
                {
                    b.Property<int>("MovieHallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieHallId"));

                    b.Property<int>("SeatAmount")
                        .HasColumnType("int");

                    b.Property<bool>("occupied")
                        .HasColumnType("bit");

                    b.HasKey("MovieHallId");

                    b.ToTable("MovieHalls");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.Movies", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("MovieDuration")
                        .HasColumnType("int");

                    b.Property<int?>("MovieHallId")
                        .HasColumnType("int");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("MovieHallId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int?>("MovieHallId")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("MovieHallId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.Movies", b =>
                {
                    b.HasOne("Cinema2026.Repo.Models.MovieHall", null)
                        .WithMany("MovieId")
                        .HasForeignKey("MovieHallId");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.Person", b =>
                {
                    b.HasOne("Cinema2026.Repo.Models.MovieHall", null)
                        .WithMany("PersonId")
                        .HasForeignKey("MovieHallId");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.MovieHall", b =>
                {
                    b.Navigation("MovieId");

                    b.Navigation("PersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
